[pytest]
testpaths = src
python_files = test_*.py
addopts = --strict-markers -p no:cacheprovider --import-mode=importlib
markers =
    copyright: copyright check
    linter: linter check
    flake8: flake8 check
    pep257: pep257 check
    launch_test: launch_testing tests
