controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trigger_controller:
      type: position_controllers/JointGroupPositionController

    flywheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    pusher_controller:
      type: velocity_controllers/JointGroupVelocityController

trigger_controller:
  ros__parameters:
    joints:
      - trigger_joint

flywheel_controller:
  ros__parameters:
    joints:
      - flywheel_left_joint
      - flywheel_right_joint

pusher_controller:
  ros__parameters:
    joints:
      - dart_pusher_joint
