controller_manager:
  ros__parameters:
    update_rate: 100 # Increased rate to match sim better
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trigger_controller:
      type: position_controllers/JointGroupPositionController

trigger_controller:
  ros__parameters:
    joints:
      - trigger_joint
